volumes:
  harmonaize_local_postgres_data: {}
  harmonaize_local_postgres_data_backups: {}
  harmonaize_local_redis_data: {}
  nominatim_data: {}
  nominatim_flatnode: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: harmonaize_local_django
    container_name: harmonaize_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: harmonaize_production_postgres
    container_name: harmonaize_local_postgres
    volumes:
      - harmonaize_local_postgres_data:/var/lib/postgresql/data
      - harmonaize_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: harmonaize_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: harmonaize_local_redis
    volumes:
      - harmonaize_local_redis_data:/data

  celeryworker:
    <<: *django
    image: harmonaize_local_celeryworker
    container_name: harmonaize_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: harmonaize_local_celerybeat
    container_name: harmonaize_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: harmonaize_local_flower
    container_name: harmonaize_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  nominatim:
    build:
      context: .
      dockerfile: ./compose/local/nominatim/Dockerfile
    image: harmonaize_local_nominatim
    container_name: harmonaize_local_nominatim
    environment:
      - NOMINATIM_PASSWORD=harmonaize_secure_pass_2024
      
      # Global dataset for comprehensive worldwide coverage
      - PBF_URL=https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
      
      # Import settings optimized for global dataset
      - UPDATE_MODE=import
      - IMPORT_STYLE=street      # Includes health facilities
      - IMPORT_WIKIPEDIA=false
      - IMPORT_US_POSTCODES=false
      - IMPORT_GB_POSTCODES=false
      - IMPORT_TIGER_ADDRESSES=false
      
      # Enable full geocoding capabilities
      - REVERSE_ONLY=false
      - FREEZE=false
      
      # Performance settings for global dataset
      - THREADS=8
      - GUNICORN_WORKERS=4
      
      # Memory settings optimized for global dataset (requires 32GB+ RAM)
      - POSTGRES_SHARED_BUFFERS=8GB
      - POSTGRES_MAINTENANCE_WORK_MEM=16GB
      - POSTGRES_AUTOVACUUM_WORK_MEM=4GB
      - POSTGRES_WORK_MEM=1GB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=24GB
      - POSTGRES_SYNCHRONOUS_COMMIT=off
      - POSTGRES_MAX_WAL_SIZE=8GB
      - POSTGRES_CHECKPOINT_TIMEOUT=30min
      - POSTGRES_CHECKPOINT_COMPLETION_TARGET=0.9
      - POSTGRES_WAL_BUFFERS=128MB
      - POSTGRES_RANDOM_PAGE_COST=1.1
      - POSTGRES_MIN_WAL_SIZE=4GB
      - POSTGRES_CHECKPOINT_SEGMENTS=256
      
    env_file:
      - ./.envs/.local/.nominatim  # Store SCP credentials here
    ports:
      - "8080:8080"
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main
      - nominatim_flatnode:/nominatim/flatnode
    shm_size: '16gb'
    deploy:
      resources:
        limits:
          memory: 40G    # Global dataset requires significant RAM
        reservations:
          memory: 16G
    
    # Health check with extended timeout for global dataset
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 120s
      timeout: 60s
      retries: 15
      start_period: 14400s # 4 hours startup time for global dataset