# Generated by Django 5.0.13 on 2025-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the location.', max_length=100),
        ),
    ]
