# Generated by Django 5.0.13 on 2025-09-30 13:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attribute_description_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='Vector embedding of the description for semantic similarity search', null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='Vector embedding of the variable name for semantic similarity search', null=True),
        ),
    ]
