# Generated by Django 5.0.13 on 2025-09-30 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding of the description for semantic similarity search', null=True, size=None),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding of the variable name for semantic similarity search', null=True, size=None),
        ),
    ]
