# Generated by Django 5.0.13 on 2025-06-01 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('climate', 'Climate'), ('geolocation', 'Geolocation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude in decimal degrees (-90 to 90).', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude in decimal degrees (-180 to 180).', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
