# Generated by Django 5.0.13 on 2025-06-27 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attribute_category_alter_location_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the study', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the study')),
                ('principal_investigator', models.CharField(blank=True, help_text='Principal investigator name', max_length=200)),
                ('study_type', models.CharField(choices=[('clinical_trial', 'Clinical Trial'), ('cohort', 'Cohort Study'), ('registry', 'Registry'), ('cross_sectional', 'Cross-sectional Study'), ('case_control', 'Case-Control Study'), ('other', 'Other')], help_text='Type of research study', max_length=50)),
                ('has_ethical_approval', models.BooleanField(default=False, help_text='Does this study have ethical/IRB approval?')),
                ('data_use_permissions', models.JSONField(blank=True, default=list, help_text='Data use permissions based on Data Use Ontology')),
                ('ethics_approval_number', models.CharField(blank=True, help_text='Ethics committee/IRB approval number', max_length=100)),
                ('has_dates', models.BooleanField(default=False, help_text='Does the study include date/time variables?')),
                ('has_locations', models.BooleanField(default=False, help_text='Does the study include location data?')),
                ('needs_geolocation', models.BooleanField(default=False, help_text='Do you need to geolocate addresses/facilities?')),
                ('needs_climate_linkage', models.BooleanField(default=False, help_text='Do you want to link climate data?')),
                ('source_codebook', models.FileField(blank=True, help_text='Upload your source codebook (CSV, Excel, SPSS, Stata, JSON, DB, etc.)', null=True, upload_to='studies/codebooks/')),
                ('source_codebook_format', models.CharField(blank=True, help_text='Auto-detected format of the source codebook file', max_length=20)),
                ('protocol_file', models.FileField(blank=True, help_text='Upload study protocol or additional documentation', null=True, upload_to='studies/protocols/')),
                ('additional_files', models.FileField(blank=True, help_text='Upload additional study documentation', null=True, upload_to='studies/additional/')),
                ('sample_size', models.PositiveIntegerField(blank=True, help_text='Approximate sample size (if known)', null=True)),
                ('study_period_start', models.DateField(blank=True, help_text='Study start date (optional)', null=True)),
                ('study_period_end', models.DateField(blank=True, help_text='Study end date (optional)', null=True)),
                ('geographic_scope', models.CharField(blank=True, help_text="Geographic scope (optional - e.g., 'Global', 'USA', 'Sub-Saharan Africa')", max_length=200)),
                ('status', models.CharField(choices=[('created', 'Created'), ('codebook_uploaded', 'Source Codebook Uploaded'), ('variables_extracted', 'Variables Extracted'), ('variables_mapped', 'Variables Mapped'), ('harmonized', 'Harmonized'), ('completed', 'Completed')], default='created', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL)),
                ('variables', models.ManyToManyField(blank=True, help_text='Variables/attributes included in this study', related_name='studies', to='core.attribute')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['-created_at'],
            },
        ),
    ]
