# Generated by Django 5.0.13 on 2026-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectinvitation_projectmembership_project_members'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('name', 'project')},
        ),
    ]
