# Generated by Django 5.0.13 on 2025-06-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_attribute_category_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country of the location.", max_length=100
            ),
        ),
    ]
