# Generated by Django 5.0.13 on 2025-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attribute_description_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description_tsne_x',
            field=models.FloatField(blank=True, help_text='X coordinate from t-SNE projection of description embedding', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='description_tsne_y',
            field=models.FloatField(blank=True, help_text='Y coordinate from t-SNE projection of description embedding', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_tsne_x',
            field=models.FloatField(blank=True, help_text='X coordinate from t-SNE projection of name embedding', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_tsne_y',
            field=models.FloatField(blank=True, help_text='Y coordinate from t-SNE projection of name embedding', null=True),
        ),
    ]
