# Generated by Django 5.0.13 on 2025-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='source_type',
            field=models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='source', max_length=10),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='variable_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('variable_name', 'source_type')},
        ),
    ]
