# Generated by Django 5.0.13 on 2026-01-21 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_study_unique_name_per_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='additional_files',
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload study documentation', upload_to='studies/documents/')),
                ('document_type', models.CharField(choices=[('additional', 'Additional Document'), ('consent', 'Consent Form'), ('questionnaire', 'Questionnaire'), ('data_dictionary', 'Data Dictionary'), ('ethics', 'Ethics Approval'), ('other', 'Other')], default='additional', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description of the document', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.study')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
