# Generated by Django 5.0.13 on 2025-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attribute_source_type_alter_attribute_variable_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='source_codebook',
        ),
        migrations.RemoveField(
            model_name='study',
            name='source_codebook_format',
        ),
        migrations.AddField(
            model_name='study',
            name='codebook',
            field=models.FileField(blank=True, help_text='Upload your codebook (CSV, Excel, SPSS, Stata, JSON, DB, etc.)', null=True, upload_to='studies/codebooks/'),
        ),
        migrations.AddField(
            model_name='study',
            name='codebook_format',
            field=models.CharField(blank=True, help_text='Auto-detected format of the codebook file', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='study_purpose',
            field=models.CharField(choices=[('source', 'Source Study'), ('target', 'Target Study')], default='source', help_text='Whether this is a source study (data to harmonize) or target study (harmonization target)', max_length=10),
        ),
    ]
