# Generated by Django 5.0.13 on 2025-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_study_source_codebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('codebook_uploaded', 'Source Codebook Uploaded'), ('variables_extracted', 'Variables Extracted'), ('variables_mapped', 'Variables Mapped'), ('harmonised', 'Harmonised'), ('completed', 'Completed')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_purpose',
            field=models.CharField(choices=[('source', 'Source Study'), ('target', 'Target Study')], default='source', help_text='Whether this is a source study (data to harmonise) or target study (harmonisation target)', max_length=10),
        ),
    ]
