# Generated by Django 5.0.13 on 2025-06-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_geocodingbatch_geocodingresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeocodingBatch',
        ),
        migrations.AlterUniqueTogether(
            name='geocodingresult',
            unique_together=set(),
        ),
    ]
