# Generated by Django 5.0.13 on 2025-06-30 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0006_geocodingresult_hdx_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodingresult',
            name='coordinate_variance',
            field=models.FloatField(blank=True, help_text='Variance between different geocoding sources', null=True),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='distance_confidence',
            field=models.FloatField(blank=True, help_text='Confidence based on coordinate clustering', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='recommended_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='source_reliability_score',
            field=models.FloatField(blank=True, help_text='Reliability score of the recommended source', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='validated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='reverse_geocoding_score',
            field=models.FloatField(blank=True, help_text='Score from reverse geocoding validation (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='validation_metadata',
            field=models.JSONField(blank=True, help_text='Enhanced validation data including reverse geocoding results and AI analysis', null=True),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['validation_status'], name='geolocation_validat_cf953b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['confidence_score'], name='geolocation_confide_249551_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['created_at'], name='geolocation_created_08fa2d_idx'),
        ),
    ]
