# Generated by Django 5.0.13 on 2025-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0007_geocodingresult_coordinate_variance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geocodingresult',
            table='geolocation_geocodingresult',
        ),
        migrations.AlterModelTable(
            name='hdxhealthfacility',
            table='geolocation_hdxhealthfacility',
        ),
        migrations.AlterModelTable(
            name='validationdataset',
            table='geolocation_validationdataset',
        ),
    ]
