# Generated by Django 5.0.13 on 2025-08-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingschema',
            name='name',
        ),
    ]
