# Generated by Django 5.0.13 on 2025-08-18 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('health', '0002_rawdatacolumn_mapped_variable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatafile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum of the uploaded file content', max_length=64),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='detected_columns',
            field=models.JSONField(blank=True, default=list, help_text='Detected column names from the file header'),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='expected_attributes',
            field=models.JSONField(blank=True, default=list, help_text="Expected attribute names from the study's codebook at upload time"),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='extra_columns',
            field=models.JSONField(blank=True, default=list, help_text="Columns present in the file but not found in the study's attributes"),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='has_attribute_mismatches',
            field=models.BooleanField(default=False, help_text='Whether detected columns differ from expected attributes'),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='missing_attributes',
            field=models.JSONField(blank=True, default=list, help_text='Attributes expected by the study but missing from the file'),
        ),
        migrations.AddIndex(
            model_name='rawdatafile',
            index=models.Index(fields=['study', 'checksum'], name='rdfile_study_checksum_idx'),
        ),
    ]
