# Generated by Django 5.0.13 on 2025-08-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_mappingschema_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingschema',
            name='create_related_patient',
        ),
        migrations.RemoveField(
            model_name='mappingschema',
            name='datetime_attribute',
        ),
        migrations.RemoveField(
            model_name='mappingschema',
            name='patient_id_attribute',
        ),
        migrations.RemoveField(
            model_name='mappingschema',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='related_relation_type',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse/Partner'), ('sibling', 'Sibling'), ('other', 'Other')], help_text='Relation type (only for related patient id role)', max_length=20),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='role',
            field=models.CharField(choices=[('value', 'Value'), ('patient_id', 'Patient ID'), ('datetime', 'Date/Time'), ('related_patient_id', 'Related Patient ID')], default='value', max_length=32),
        ),
    ]
