# Generated by Django 5.0.13 on 2025-08-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_rawdatafile_checksum_rawdatafile_detected_columns_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawdatafile',
            name='rdfile_study_checksum_idx',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='detected_columns',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='expected_attributes',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='extra_columns',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='has_attribute_mismatches',
        ),
        migrations.RemoveField(
            model_name='rawdatafile',
            name='missing_attributes',
        ),
        migrations.AlterField(
            model_name='rawdatafile',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('processed', 'Processed'), ('processing', 'Processing'), ('ingested', 'Ingested'), ('processed_with_errors', 'Processed with Errors'), ('error', 'Processing Error')], default='uploaded', max_length=30),
        ),
    ]
