# Generated by Django 5.0.13 on 2025-08-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('health', '0003_remove_mappingschema_create_related_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingschema',
            name='auto_populate_enabled',
            field=models.BooleanField(default=False, help_text='Whether to auto-populate mapping rules based on universal settings'),
        ),
        migrations.AddField(
            model_name='mappingschema',
            name='universal_datetime',
            field=models.ForeignKey(blank=True, help_text='Default source attribute to use as datetime for all mappings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_universal_datetime', to='core.attribute'),
        ),
        migrations.AddField(
            model_name='mappingschema',
            name='universal_patient_id',
            field=models.ForeignKey(blank=True, help_text='Default source attribute to use as patient ID for all mappings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_universal_patient_id', to='core.attribute'),
        ),
        migrations.AddField(
            model_name='mappingschema',
            name='universal_relation_type',
            field=models.CharField(choices=[('self', 'Self'), ('child', 'Child'), ('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse/Partner'), ('sibling', 'Sibling'), ('other', 'Other')], default='self', help_text='Default relationship type for related patient mappings', max_length=20),
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='target_attribute',
            field=models.ForeignKey(blank=True, help_text='Attribute from the target study', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_target_in_rules', to='core.attribute'),
        ),
    ]
