# Generated by Django 5.0.13 on 2025-08-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_rawdatafile_rdfile_study_checksum_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatafile',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validation_error', 'Validation Error'), ('validated', 'Validated'), ('processed', 'Processed'), ('processing', 'Processing'), ('ingestion_error', 'Ingestion Error'), ('ingested', 'Ingested'), ('processed_with_errors', 'Processed with Errors'), ('error', 'Processing Error')], default='uploaded', max_length=30),
        ),
    ]
