# Generated by Django 5.0.13 on 2025-08-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('health', '0004_mappingschema_auto_populate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingrule',
            name='datetime_attribute',
            field=models.ForeignKey(blank=True, help_text='DateTime attribute to use for this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_datetime_for_rules', to='core.attribute'),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='patient_id_attribute',
            field=models.ForeignKey(blank=True, help_text='Patient ID attribute to use for this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_patient_id_for_rules', to='core.attribute'),
        ),
    ]
