# Generated by Django 5.0.13 on 2025-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_add_patient_id_datetime_to_mapping_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingrule',
            name='not_mappable',
            field=models.BooleanField(default=False, help_text='Mark this variable as not mappable to any target variable'),
        ),
    ]
