# Generated by Django 5.0.13 on 2025-08-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_mappingrule_not_mappable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingrule',
            name='use_custom_settings',
            field=models.BooleanField(default=False, help_text='Override universal settings with custom patient ID/datetime for this mapping'),
        ),
    ]
