# Generated by Django 5.0.13 on 2025-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_rawdatafile_transformation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatafile',
            name='eda_cache_source',
            field=models.JSONField(blank=True, help_text='Cached EDA summary for source (raw) data', null=True),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='eda_cache_source_generated_at',
            field=models.DateTimeField(blank=True, help_text='When source EDA cache was last generated', null=True),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='eda_cache_transformed',
            field=models.JSONField(blank=True, help_text='Cached EDA summary for transformed data', null=True),
        ),
        migrations.AddField(
            model_name='rawdatafile',
            name='eda_cache_transformed_generated_at',
            field=models.DateTimeField(blank=True, help_text='When transformed EDA cache was last generated', null=True),
        ),
    ]
