# Generated by Django 5.0.13 on 2025-08-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_mappingrule_use_custom_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingrule',
            name='use_custom_settings',
        ),
    ]
