# Generated by Django 5.0.13 on 2025-07-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_study_status_alter_study_study_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(max_length=100)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.observation')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate.climatesource')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_temperature', models.FloatField(blank=True, null=True)),
                ('total_rainfall', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('time_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timedimension')),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate.climatesource')),
            ],
        ),
    ]
