# Generated by Django 5.2.1 on 2025-11-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climatedatarequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="climatedatasource",
            name="created_by",
        ),
    ]
