# Generated by Django 5.2.1 on 2025-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_remove_direct_user_relationships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatevariable",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Variable category (e.g., temperature, precipitation, humidity, or custom types). Not restricted to predefined choices - users can define their own categories.",
                max_length=100,
            ),
        ),
    ]
