# Generated by Django 5.0.13 on 2026-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Your organization or institution', max_length=255, verbose_name='Organization'),
        ),
    ]
