FROM mediagis/nominatim:4.4

USER root

# Install aria2c
RUN curl -L https://github.com/P3TERX/Aria2-Pro-Core/releases/download/1.36.0_2021.08.22/aria2-1.36.0-static-linux-amd64.tar.gz \
    -o aria2.tar.gz && \
    tar -xzf aria2.tar.gz && \
    cp aria2c /usr/local/bin/ && \
    chmod +x /usr/local/bin/aria2c && \
    rm -rf aria2*

# Copy init script
COPY compose/local/nominatim/init-aria2c.sh /app/init-aria2c.sh

# Create nominatim user
RUN useradd -ms /bin/bash nominatim

USER nominatim

ENTRYPOINT ["/app/init-aria2c.sh"]
