FROM mediagis/nominatim:4.4
USER root

# Download working aria2 static binary from P3TERX
RUN curl -L https://github.com/P3TERX/Aria2-Pro-Core/releases/download/1.36.0_2021.08.22/aria2-1.36.0-static-linux-amd64.tar.gz \
    -o aria2.tar.gz && \
    tar -xzf aria2.tar.gz && \
    cp aria2c /usr/local/bin/ && \
    chmod +x /usr/local/bin/aria2c && \
    rm -rf aria2*

COPY compose/local/nominatim/init-aria2c.sh /app/init-aria2c.sh
RUN chmod +x /app/init-aria2c.sh && cp /app/init-aria2c.sh /app/init.sh

# Remove this line - let the original startup script handle user switching
# USER nominatim

ENTRYPOINT ["/app/start.sh"]