FROM mediagis/nominatim:4.4

USER root

# Install aria2c for faster parallel downloads
RUN curl -L https://github.com/P3TERX/Aria2-Pro-Core/releases/download/1.36.0_2021.08.22/aria2-1.36.0-static-linux-amd64.tar.gz \
    -o aria2.tar.gz && \
    tar -xzf aria2.tar.gz && \
    cp aria2c /usr/local/bin/ && \
    chmod +x /usr/local/bin/aria2c && \
    rm -rf aria2*

# Copy and configure custom initialization script
COPY compose/local/nominatim/init-aria2c.sh /app/init-aria2c.sh
RUN chmod +x /app/init-aria2c.sh && cp /app/init-aria2c.sh /app/init.sh

ENTRYPOINT ["/app/start.sh"]