# Generated by Django 5.0.13 on 2025-08-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatacolumn',
            name='mapped_variable',
            field=models.ForeignKey(blank=True, help_text='Study variable this column maps to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.attribute'),
        ),
    ]
