# Generated by Django 5.0.13 on 2026-05-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSyncLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_name', models.CharField(default='default', max_length=100, unique=True)),
                ('locked_by_task_id', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis sync lock',
                'verbose_name_plural': 'Analysis sync locks',
            },
        ),
        migrations.CreateModel(
            name='AnalysisExportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('watermark_before', models.DateTimeField(blank=True, null=True)),
                ('watermark_after', models.DateTimeField(blank=True, null=True)),
                ('processed_studies', models.PositiveIntegerField(default=0)),
                ('processed_attributes', models.PositiveIntegerField(default=0)),
                ('processed_target_studies', models.PositiveIntegerField(default=0)),
                ('generated_parquet_files', models.PositiveIntegerField(default=0)),
                ('synced_users_count', models.PositiveIntegerField(default=0)),
                ('synced_projects_count', models.PositiveIntegerField(default=0)),
                ('uploaded_objects_count', models.PositiveIntegerField(default=0)),
                ('artifact_manifest', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_export_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_export_runs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_analysis_exports', 'Can manage analysis exports')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisScheduleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_schedule_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis schedule configuration',
                'verbose_name_plural': 'Analysis schedule configurations',
            },
        ),
        migrations.CreateModel(
            name='AnalysisDatasetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dataset_shape', models.CharField(choices=[('long', 'Long'), ('wide', 'Wide')], default='long', max_length=10)),
                ('max_lag_value', models.PositiveIntegerField(default=0)),
                ('deidentify', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('climate_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_climate', to='core.attribute')),
                ('confounder_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_confounders', to='core.attribute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_dataset_templates_created', to=settings.AUTH_USER_MODEL)),
                ('location_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_locations', to='core.attribute')),
                ('outcome_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_outcomes', to='core.attribute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_dataset_templates', to='core.project')),
                ('source_studies', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_sources', to='core.study')),
                ('target_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_dataset_templates', to='core.study')),
            ],
            options={
                'ordering': ['project__name', 'target_study__name', 'name'],
                'unique_together': {('project', 'target_study', 'name')},
            },
        ),
    ]
