# Generated by Django 5.0.13 on 2026-03-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisexportrun_parquet_sync_fields'),
        ('core', '0004_study_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDatasetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dataset_shape', models.CharField(choices=[('long', 'Long'), ('wide', 'Wide')], default='long', max_length=10)),
                ('max_lag_value', models.PositiveIntegerField(default=0)),
                ('deidentify', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('climate_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_climate', to='core.attribute')),
                ('confounder_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_confounders', to='core.attribute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_dataset_templates_created', to=settings.AUTH_USER_MODEL)),
                ('location_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_locations', to='core.attribute')),
                ('outcome_attributes', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_outcomes', to='core.attribute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_dataset_templates', to='core.project')),
                ('source_studies', models.ManyToManyField(blank=True, related_name='analysis_dataset_template_sources', to='core.study')),
                ('target_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_dataset_templates', to='core.study')),
            ],
            options={
                'ordering': ['project__name', 'target_study__name', 'name'],
                'unique_together': {('project', 'target_study', 'name')},
            },
        ),
    ]
