# Generated by Django 5.0.13 on 2025-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HDXDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(db_index=True, max_length=200)),
                ("facility_type", models.CharField(blank=True, max_length=100)),
                ("ownership", models.CharField(blank=True, max_length=100)),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("hdx_longitude", models.FloatField()),
                ("hdx_latitude", models.FloatField()),
                ("source", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facility_name"], name="geolocation_facilit_f35fde_idx"
                    ),
                    models.Index(
                        fields=["country", "facility_name"],
                        name="geolocation_country_f5de6c_idx",
                    ),
                ],
                "unique_together": {("facility_name", "country")},
            },
        ),
        migrations.CreateModel(
            name="ValidationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(db_index=True, max_length=200)),
                ("final_lat", models.FloatField()),
                ("final_long", models.FloatField()),
                ("source", models.CharField(max_length=50)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("city_town", models.CharField(blank=True, max_length=100)),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("suburb_village", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=100)),
                ("house_number", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location_name"], name="geolocation_locatio_6b2d7d_idx"
                    ),
                    models.Index(
                        fields=["country", "location_name"],
                        name="geolocation_country_13b8ce_idx",
                    ),
                ],
                "unique_together": {("location_name", "country")},
            },
        ),
    ]
