# Generated by Django 5.0.13 on 2025-12-10 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HDXHealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(db_index=True, max_length=500)),
                ('facility_type', models.CharField(blank=True, max_length=200)),
                ('ownership', models.CharField(blank=True, max_length=200)),
                ('ward', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('hdx_longitude', models.FloatField()),
                ('hdx_latitude', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HDX Health Facility',
                'verbose_name_plural': 'HDX Health Facilities',
                'db_table': 'geolocation_hdxhealthfacility',
                'indexes': [models.Index(fields=['facility_name'], name='geolocation_facilit_84f3ce_idx'), models.Index(fields=['country', 'facility_name'], name='geolocation_country_ca91b2_idx'), models.Index(fields=['facility_type'], name='geolocation_facilit_b4ef19_idx'), models.Index(fields=['district', 'facility_name'], name='geolocation_distric_0e09c7_idx')],
                'unique_together': {('facility_name', 'country', 'district')},
            },
        ),
        migrations.CreateModel(
            name='GeocodingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=500)),
                ('arcgis_lat', models.FloatField(blank=True, null=True)),
                ('arcgis_lng', models.FloatField(blank=True, null=True)),
                ('arcgis_success', models.BooleanField(default=False)),
                ('arcgis_error', models.TextField(blank=True)),
                ('arcgis_raw_response', models.JSONField(blank=True, null=True)),
                ('google_lat', models.FloatField(blank=True, null=True)),
                ('google_lng', models.FloatField(blank=True, null=True)),
                ('google_success', models.BooleanField(default=False)),
                ('google_error', models.TextField(blank=True)),
                ('google_raw_response', models.JSONField(blank=True, null=True)),
                ('nominatim_lat', models.FloatField(blank=True, null=True)),
                ('nominatim_lng', models.FloatField(blank=True, null=True)),
                ('nominatim_success', models.BooleanField(default=False)),
                ('nominatim_error', models.TextField(blank=True)),
                ('nominatim_raw_response', models.JSONField(blank=True, null=True)),
                ('hdx_lat', models.FloatField(blank=True, null=True)),
                ('hdx_lng', models.FloatField(blank=True, null=True)),
                ('hdx_success', models.BooleanField(default=False)),
                ('hdx_error', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('needs_review', 'Needs Manual Review')], default='pending', max_length=20)),
                ('selected_source', models.CharField(blank=True, max_length=20)),
                ('final_lat', models.FloatField(blank=True, null=True)),
                ('final_lng', models.FloatField(blank=True, null=True)),
                ('coordinate_variance', models.FloatField(blank=True, help_text='Variance between different geocoding sources', null=True)),
                ('parsed_location_data', models.JSONField(blank=True, help_text='Parsed location components (country, city, facility) from intelligent parsing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocoding_results', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Link to core Location model', on_delete=django.db.models.deletion.CASCADE, related_name='geocoding_results', to='core.location')),
                ('hdx_facility_match', models.ForeignKey(blank=True, help_text='Matched HDX facility if found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.hdxhealthfacility')),
            ],
            options={
                'db_table': 'geolocation_geocodingresult',
            },
        ),
        migrations.CreateModel(
            name='ValidatedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=500)),
                ('final_lat', models.FloatField()),
                ('final_long', models.FloatField()),
                ('source', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('city_town', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('suburb_village', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validated Location',
                'verbose_name_plural': 'Validated Locations (POI Arsenal)',
                'db_table': 'geolocation_validationdataset',
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Overall confidence score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('api_agreement_score', models.FloatField(blank=True, help_text='How well different APIs agree on coordinates', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reverse_geocoding_score', models.FloatField(blank=True, help_text='Score from reverse geocoding validation (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('distance_confidence', models.FloatField(blank=True, help_text='Confidence based on coordinate clustering', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source_reliability_score', models.FloatField(blank=True, help_text='Reliability score of the recommended source', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recommended_lat', models.FloatField(blank=True, null=True)),
                ('recommended_lng', models.FloatField(blank=True, null=True)),
                ('recommended_source', models.CharField(blank=True, max_length=20)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected'), ('manual_override', 'Manual Override')], default='pending', max_length=20)),
                ('validation_metadata', models.JSONField(blank=True, help_text='Enhanced validation data including reverse geocoding results and AI analysis', null=True)),
                ('manual_review_notes', models.TextField(blank=True)),
                ('manual_lat', models.FloatField(blank=True, null=True)),
                ('manual_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to=settings.AUTH_USER_MODEL)),
                ('geocoding_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='geolocation.geocodingresult')),
            ],
            options={
                'db_table': 'geolocation_validation_result',
                'ordering': ['-confidence_score', 'geocoding_result__location_name'],
            },
        ),
        migrations.AddIndex(
            model_name='geocodingresult',
            index=models.Index(fields=['location_name'], name='geolocation_locatio_76e4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='geocodingresult',
            index=models.Index(fields=['validation_status'], name='geolocation_validat_22f660_idx'),
        ),
        migrations.AddIndex(
            model_name='geocodingresult',
            index=models.Index(fields=['created_at'], name='geolocation_created_d666e7_idx'),
        ),
        migrations.AddIndex(
            model_name='geocodingresult',
            index=models.Index(fields=['created_by'], name='geolocation_created_e2618d_idx'),
        ),
        migrations.AddIndex(
            model_name='validateddataset',
            index=models.Index(fields=['location_name'], name='geolocation_locatio_6b2d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='validateddataset',
            index=models.Index(fields=['country', 'location_name'], name='geolocation_country_13b8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='validateddataset',
            index=models.Index(fields=['created_by'], name='geolocation_created_e6f912_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validateddataset',
            unique_together={('location_name', 'country', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['validation_status'], name='geolocation_validat_cf953b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['confidence_score'], name='geolocation_confide_249551_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['created_at'], name='geolocation_created_08fa2d_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['created_by'], name='geolocation_created_f88044_idx'),
        ),
    ]
