# Generated by Django 5.0.13 on 2025-07-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_study_status_alter_study_study_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='GeoBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.JSONField()),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='GeolocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geolocation_data', to='core.location')),
            ],
        ),
    ]
