# Generated by Django 5.0.13 on 2025-06-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HDXDataset',
        ),
    ]
