# Generated by Django 5.0.13 on 2026-01-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='location_csv/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(default='csv', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('location_name_column', models.CharField(blank=True, help_text='Column containing location names (required)', max_length=200)),
                ('latitude_column', models.CharField(blank=True, help_text='Column containing latitude values (optional)', max_length=200)),
                ('longitude_column', models.CharField(blank=True, help_text='Column containing longitude values (optional)', max_length=200)),
                ('detected_columns', models.JSONField(default=list, help_text='List of all columns detected in the file')),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total number of data rows in the file')),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('processed', 'Processed'), ('ingested', 'Ingested'), ('error', 'Error')], default='uploaded', max_length=30)),
                ('processing_message', models.TextField(blank=True, help_text='Status message or error details')),
                ('locations_created', models.PositiveIntegerField(default=0, help_text='Number of Location objects created from this upload')),
                ('locations_skipped', models.PositiveIntegerField(default=0, help_text='Number of rows skipped (duplicates or invalid data)')),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum for duplicate detection', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location CSV Upload',
                'verbose_name_plural': 'Location CSV Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationCSVColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200)),
                ('column_index', models.PositiveIntegerField(help_text='0-based index in the file')),
                ('inferred_type', models.CharField(choices=[('text', 'Text'), ('float', 'Float'), ('integer', 'Integer'), ('date', 'Date'), ('datetime', 'DateTime')], default='text', max_length=50)),
                ('sample_values', models.JSONField(default=list, help_text='Sample values from this column for preview')),
                ('non_null_count', models.PositiveIntegerField(default=0, help_text='Number of non-null values')),
                ('unique_count', models.PositiveIntegerField(default=0, help_text='Number of unique values')),
                ('is_potential_location_name', models.BooleanField(default=False, help_text='System detected this might be a location name column')),
                ('is_potential_latitude', models.BooleanField(default=False, help_text='System detected this might be a latitude column')),
                ('is_potential_longitude', models.BooleanField(default=False, help_text='System detected this might be a longitude column')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='geolocation.locationcsvupload')),
            ],
            options={
                'verbose_name': 'Location CSV Column',
                'verbose_name_plural': 'Location CSV Columns',
                'ordering': ['column_index'],
            },
        ),
        migrations.AddIndex(
            model_name='locationcsvupload',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='geolocation_uploade_3a56c9_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcsvupload',
            index=models.Index(fields=['processing_status'], name='geolocation_process_4db1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcsvupload',
            index=models.Index(fields=['checksum'], name='geolocation_checksu_e8a76d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationcsvcolumn',
            unique_together={('upload', 'column_name')},
        ),
    ]
