# Generated by Django 5.0.13 on 2025-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_delete_hdxdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_locations', models.IntegerField(default=0)),
                ('processed_locations', models.IntegerField(default=0)),
                ('successful_geocodes', models.IntegerField(default=0)),
                ('failed_geocodes', models.IntegerField(default=0)),
                ('validated_from_dataset', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('used_arcgis', models.BooleanField(default=True)),
                ('used_google', models.BooleanField(default=True)),
                ('used_nominatim', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GeocodingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=200)),
                ('arcgis_lat', models.FloatField(blank=True, null=True)),
                ('arcgis_lng', models.FloatField(blank=True, null=True)),
                ('arcgis_success', models.BooleanField(default=False)),
                ('arcgis_error', models.TextField(blank=True)),
                ('arcgis_raw_response', models.JSONField(blank=True, null=True)),
                ('google_lat', models.FloatField(blank=True, null=True)),
                ('google_lng', models.FloatField(blank=True, null=True)),
                ('google_success', models.BooleanField(default=False)),
                ('google_error', models.TextField(blank=True)),
                ('google_raw_response', models.JSONField(blank=True, null=True)),
                ('nominatim_lat', models.FloatField(blank=True, null=True)),
                ('nominatim_lng', models.FloatField(blank=True, null=True)),
                ('nominatim_success', models.BooleanField(default=False)),
                ('nominatim_error', models.TextField(blank=True)),
                ('nominatim_raw_response', models.JSONField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('needs_review', 'Needs Manual Review')], default='pending', max_length=20)),
                ('selected_source', models.CharField(blank=True, max_length=20)),
                ('final_lat', models.FloatField(blank=True, null=True)),
                ('final_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location_name'], name='geolocation_locatio_76e4b3_idx'), models.Index(fields=['validation_status'], name='geolocation_validat_22f660_idx'), models.Index(fields=['created_at'], name='geolocation_created_d666e7_idx')],
                'unique_together': {('location_name',)},
            },
        ),
    ]
