# Generated by Django 5.0.13 on 2026-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_locationcsvupload_locationcsvcolumn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_boundary_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_boundary_lat',
            field=models.FloatField(blank=True, help_text='Centroid latitude from admin boundary match', null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_boundary_lng',
            field=models.FloatField(blank=True, help_text='Centroid longitude from admin boundary match', null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_boundary_match',
            field=models.JSONField(blank=True, help_text='Boundary match details: {source_file, feature_index, osm_id, name, admin_level}', null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_boundary_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='admin_level',
            field=models.CharField(blank=True, help_text="Administrative level (e.g., '2' for country, '4' for province, '6' for district)", max_length=10),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='boundary_validation',
            field=models.JSONField(blank=True, help_text='Validation result from boundary checking: {is_valid, actual_country, warnings, severity}', null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='location_type',
            field=models.CharField(choices=[('point', 'Point'), ('admin_boundary', 'Admin Boundary'), ('unknown', 'Unknown')], default='unknown', help_text='Type of location: point (facility/POI) or admin_boundary (province/district)', max_length=20),
        ),
    ]
