# Generated by Django 5.0.13 on 2025-06-30 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0005_hdxhealthfacility_validationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodingresult',
            name='hdx_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='hdx_facility_match',
            field=models.ForeignKey(blank=True, help_text='Matched HDX facility if found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocation.hdxhealthfacility'),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='hdx_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='hdx_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocodingresult',
            name='hdx_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geocodingresult',
            name='location_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='facility_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='facility_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='ownership',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hdxhealthfacility',
            name='ward',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='validationdataset',
            name='location_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
